### ISSUE TITLE
Adding two metrics: RR at P95 and P5

### ISSUE THREAD

**Issue by jlkephart** [Drexel-UHC/SALURBAL-Heat-Study-MS85#12]
Hi Ran - as per editors we need to add the RR at P95 and P5 as metrics throughout the app. The priority is first under the "City-specific Details" tab, then the rest of the app. 

I added the two variables to the original dataset of mortality results for the app:
[https://drexel0-my.sharepoint.com/:x:/g/personal/jlk465_drexel_edu/Ea_EnXL6vGNIksmIPTMNemsBJrWSCI-rAlPs4JaQb7OcLA?e=RBXbs1](url)

The variables we need to add
##Relative risk at 5th percentile: [RR_at_P5]
##Relative risk at 95th percentile: [RR_at_P95]

I'm back and around on slack for any Q's. Thank you!!

**Comment by rl627** [comment]
Got it! I will start working on this.

You mentioned it was time-sensitive right?

**Comment by rl627** [comment]
### Updates 
- new data imported and added to datastore
- App updated for new data in all three tabs 
- Staging link: https://drexel-uhc.shinyapps.io/MS85_staging/


@jlkephart  Let me know what you think before we move it to the public-facing URL!

**Comment by jlkephart** [comment]
Ran this is fantastic. I owe you one, thanks so much for such a quick
response!

Publish!

**Comment by rl627** [comment]
published! feel free to close this issue when you've checked! 😄

**Comment by jlkephart** [comment]
Hi Ran, sorry noticed one thing. Could you please log-transform the X-axes for the four relative risk metrics in these two tabs:

Effects of Temperature -> By Climate Zone
Effects of Temperature -> By Country

**Comment by jlkephart** [comment]
Yes, hoping to resubmit asap. If we even have only one tab done we can
submit and say "the metric is there", then keep working on the rest of it.

Thanks Ran, I appreciate it!

**Comment by ran-codes** [comment]
is there something that needs updating? I thought the RR at P95 and P5 was done?

**Comment by ran-codes** [comment]
closing because email or GH problem reopened this issue. who knkows.


👻 👻 👻 👻
